# Generated by Django 2.2 on 2019-04-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190411_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='title',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
