# Generated by Django 2.2 on 2019-04-12 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190411_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
